baseURL: "https://emartinez.net/"
pagination:
  pagerSize: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-794QH4SNC9
disqusShortname: "emartinez"

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - JSON
        - RSS
defaultContentLanguage: es
defaultContentLanguageInSubdir: true
languages:
  es:
    languageName: ":es:"
    contentDir: content/es
    disabled: false
    languageCode: "es-ES"
    languageDirection: ltr
    title: "Enrique Martínez"
    weight: 1
    params:
      homeInfoParams:
        title: Enrique Martínez
        subtitle: Junior Software Engineer
        Content: |
          **Bienvenido a mi blog!**

          Soy Enrique, un ingeniero de software que cambió la gestión de empresas por la programación.

          Después de descubrir mi pasión por la tecnología, aprendí desarrollo de software de forma
          autodidacta y en la escuela 42 durante dos años. Ahora trabajo en el sector sector
          aeroespacial, contribuyendo a proyectos que implican tecnología punta e impacto en el mundo real.

          En este blog comparto mis ideas, experiencias y reflexiones sobre mi trayectoria en el
          mundo del desarrollo de software. Tanto si eres un desarrollador, un entusiasta de la
          tecnología o simplemente un curioso, espero que encuentres aquí algo valor o inspiración.
      footer:
        text: "[¿Quién escribe estos posts?](/sobre-mi)"
    menu:
      main:
        - identifier: posts
          name: Artículos
          url: /posts/
          weight: 9
        - identifier: categories
          name: Categorías
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: contacto
          name: Contacto
          url: /contacto
          weight: 31
        - identifier: busqueda
          name: Búsqueda
          url: /busqueda
          weight: 40

  en:
    languageName: ":gb:"
    contentDir: content/en
    disabled: false
    languageCode: "en-US"
    languageDirection: ltr
    title: "Enrique Martínez"
    weight: 2
    params:
      description: "Software developer, maker and tech lover based in Spain. Currently stuying at 42 School"
      homeInfoParams:
        title: Enrique Martínez
        subtitle: Junior Software Engineer
        Content: |
          **Welcome to my blog!**

          I'm Enrique, a software engineer with a unique journey from business to programming.

          After discovering my passion for technology, I completed the rigorous curriculum at 42
          School, which fueled my love for problem-solving and innovation. Now, I work in the
          aerospace sector, contributing to projects that involve cutting-edge technology and real-world impact.

          Through this blog, I share insights, experiences, and reflections from my journey in tech. Whether you’re a fellow developer, a tech enthusiast, or simply curious, I hope you'll find value and inspiration here!
      footer:
        text: "[Who's behind these posts?](/about-me)"
    menu:
      main:
        - identifier: Posts
          name: Posts
          url: /posts/
          weight: 9
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: contact
          name: Contact
          url: /contact
          weight: 31
        - identifier: search
          name: Search
          url: /search
          weight: 40

params:
  env: production
  keywords: [Blog, Portfolio, Developer, Maker, Tech blog]
  author: Enrique Martínez
  images: 
    - "./static/bio-photo.jpg"
  DateFormat: "2 January, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  displayFullLangName: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"

  label:
    text: "Home"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/emartinez-dev"
    - name: github
      url: "https://github.com/emartinez-dev"
    - name: linkedin
      url: "https://www.linkedin.com/in/francisco-enrique-martinez/"

  analytics:
    google:
      SiteVerificationTag: "G-794QH4SNC9"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
